# Site settings
title: codig<>
email: uclidesgil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog Personal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uclidesgil.github.io" # the base hostname & protocol for your site
twitter_username: uclidesgil
github_username:  uclides
google_play: 'uclides'
google_plus_com: '109485346959707049693'  # Community link
google_plus_per: '+GDGManagua'  #Personal link
facebook_app_id: 12345

#language
index:
  es:
  en: en_index.html
android:  
  es:
  en: en_android.html  

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
excerpt_separator: ""
more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com
disqus: true
disqus_shortname: 'uclides'

# Build settings
markdown: kramdown
